export const hiringCompanies = [
  { name: "ISRO", logo: "/ISRO-Black.svg" },
  { name: "Indian Oil Corporation", logo: "/Indian_Oil_Corporation-Logo.wine.svg" },
  { name: "ONGC", logo: "/Oil_and_Natural_Gas_Corporation-Logo.wine.svg" },
  { name: "Apollo Tyres", logo: "/apollo-tyres-logo.svg" },
  { name: "Britannia Industries", logo: "/britannia-industries-logo.svg" },
  { name: "Bronson Laboratories", logo: "/bronson-laboratories.svg" },
  { name: "DRDO", logo: "/drdo-official-seeklogo.svg" },
  { name: "HDFC Bank", logo: "/hdfc-bank-logo.svg" },
  { name: "Infosys", logo: "/infosys-3.svg" },
  { name: "Jubilant Foodworks", logo: "/jubilant-foodworks-seeklogo-2.svg" },
  { name: "Kia Motors", logo: "/kia-motors-1.svg" },
  { name: "Larsen & Toubro", logo: "/larsen-toubro-logo-1.svg" },
  { name: "Mahindra", logo: "/mahindra-mahindra-logo.svg" },
  { name: "Maruti Suzuki", logo: "/maruti-suzuki-logo.svg" },
  { name: "Reliance Industries", logo: "/reliance-industries-logo-1.svg" },
  { name: "TCS", logo: "/tcs.svg" },
  { name: "Titan", logo: "/titan-2.svg" },
]
